name: appcs-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of rg- Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      appcsName:
        description: 'Name of the appcs- resource - Example: appcs-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      appcsSku:
        description: 'Sku of the appcs- resource - Example: free'
        required: false
        type: choice
        default: 'free'
        options:
          - 'free'
          - 'standard'
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.appcsName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/appcs-appconfigurationstore.json --parameters  ${{ github.event.inputs.armPath }}/appcs-appconfigurationstore.parameters.json -name "${{ github.event.inputs.appcsName }}" -sku "${{ github.event.inputs.appcsSku }}"
                    