name: dotnet-test-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      scriptsPath:
        description: 'Path to PowerShell and CMD scripts - Default: github.workspace/scripts'
        required: false
        type: string
        default: '${{ github.workspace }}/scripts'
      srcPath:
        description: 'Path to .NET source project - Default: github.workspace/src'
        required: false
        type: string
        default: '${{ github.workspace }}/src'
      srcProject:
        description: 'Mask to .NET source project file name - Default: *.csproj'
        required: false
        type: string
        default: '*.csproj'
      dotnetVersion:
        description: 'Mask to .NET version - Default: 6.x'
        required: false
        type: string
        default: '6.x'
      rgEnvironment:
        description: 'Environment string of the Azure Resource Group - Default: Development'
        required: false
        type: string
        default: 'Development'
      appcsEnvironmentVariable:
        description: 'Environment variable key of the Azure App Configuration resource - Default: AZURE_APP_CONFIGURATION_CONNECTION'
        required: false
        type: string
        default: 'AZURE_APP_CONFIGURATION_CONNECTION'
      appcsConnection:
        description: 'Connection string of the Azure App Configuration resource - Default: none'
        required: false
        type: string
        default: 'none'
      stEnvironmentVariable:
        description: 'Environment variable key of the Azure Storage Account resource - Default: AZURE_STORAGE_CONNECTION'
        required: false
        type: string
        default: 'AZURE_STORAGE_CONNECTION'
      stConnection:
        description: 'Connection string of the Azure Storage Account resource - Default: none'
        required: false
        type: string
        default: 'none'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: use .net ${{ github.event.inputs.dotnetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ github.event.inputs.dotnetVersion }}
    - name: dotnet test
      run: dotnet test ${{ github.event.inputs.srcPath }}/**/${{ github.event.inputs.srcProject }}
      env:
        ${{ github.event.inputs.appcsEnvironmentVariable }}: ${{ github.event.inputs.appcsConnection }}
        ${{ github.event.inputs.stEnvironmentVariable }}: ${{ github.event.inputs.stConnection }}
        ASPNETCORE_ENVIRONMENT: ${{ github.event.inputs.rgEnvironment }}
        DOTNET_ENVIRONMENT: ${{ github.event.inputs.rgEnvironment }}
        AZURE_FUNCTIONS_ENVIRONMENT: ${{ github.event.inputs.rgEnvironment }}
                    