name: dotnet-pack-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      scriptsPath:
        description: 'Path to PowerShell and CMD scripts - Default: github.workspace/scripts'
        required: false
        type: string
        default: '${{ github.workspace }}/scripts'
      srcPath:
        description: 'Path to .NET source project - Default: github.workspace/src'
        required: false
        type: string
        default: '${{ github.workspace }}/src'
      srcProject:
        description: 'Mask to .NET source project file name - Default: *.csproj'
        required: false
        type: string
        default: '*.csproj'
      dotnetVersion:
        description: 'Mask to .NET version - Default: 6.x'
        required: false
        type: string
        default: '6.x'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: use .net ${{ github.event.inputs.dotnetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ github.event.inputs.dotnetVersion }}
    - name: Set-Version.ps1
      shell: powershell
      run: ${{ github.event.inputs.scriptsPath }}/Set-Version.ps1 --Path ${{ github.event.inputs.srcPath }} --VersionToReplace ${{ github.event.inputs.srcVersionToReplace }}
    - name: dotnet pack
      run: dotnet pack ${{ github.event.inputs.srcPath }}/**/${{ github.event.inputs.srcProject }} --output ${{ github.event.inputs.artifactsPath }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.inputs.artifactsPath }}
        name: drop
                    