name: dotnet-build-steps.yml

on:
  workflow_call:
    inputs:
      scriptsPath:
        description: 'Path to PowerShell and CMD scripts - Default: github.workspace/scripts'
        required: false
        type: string
        default: '${{ github.workspace }}/scripts'
      srcPath:
        description: 'Path to .NET source project - Default: github.workspace/src'
        required: false
        type: string
        default: '${{ github.workspace }}/src'
      srcProject:
        description: 'Mask to .NET source project file name - Default: *.csproj'
        required: false
        type: string
        default: '*.csproj'
      srcVersionToReplace:
        description: 'Version string to find-and-replace in packaging/assembly files - Default: 1.0.0'
        required: false
        type: string
        default: '1.0.0'
      buildConfiguration:
        description: 'dotnet build --configuration value - Example: Release'
        required: false
        type: string
        default: 'Release'
      dotnetVersion:
        description: 'Mask to .NET version - Default: 6.x'
        required: false
        type: string
        default: '6.x'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: use .net ${{ github.event.inputs.dotnetVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ github.event.inputs.dotnetVersion }}
    - name: Set-Version.ps1
      shell: powershell
      run: ${{ github.event.inputs.scriptsPath }}/Set-Version.ps1 --Path ${{ github.event.inputs.srcPath }} --VersionToReplace ${{ github.event.inputs.srcVersionToReplace }}
    - name: dotnet restore
      run: dotnet restore ${{ github.event.inputs.srcPath }}/**/${{ github.event.inputs.srcProject }}
    - name: dotnet build
      run: dotnet build ${{ github.event.inputs.srcPath }}/**/${{ github.event.inputs.srcProject }} --configuration ${{ github.event.inputs.buildConfiguration }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.inputs.artifactsPath }}
        name: drop
                    