name: func-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      appiKey:
        description: 'Key (guid) of the appi resource - Example: 00000000-0000-0000-0000-000000000000'
        required: true
        type: string
      appiConnection:
        description: 'Connection string of the appi resource - Example: InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://REGION.in.applicationinsights.azure.com...'
        required: true
        type: string
      rgEnvironment:
        description: 'Environment string of the Azure Resource Group - Default: Development'
        required: false
        type: string
        default: 'Development'
      funcName:
        description: 'Name of the func- resource to deploy - Example: func-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      funcVersion:
        description: 'Runtime Version of the func- resource to deploy - Example: 4'
        required: false
        type: string
        default: '4'
      stName:
        description: 'Name of the st- resource this func- resource depends - Example: stPRODUCTENVIRONMENT001'
        required: true
        type: string
      workName:
        description: 'Name of the work- resource this func- resource depends - Example: work-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.funcName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/func-functionsapp.json --parameters  ${{ github.event.inputs.armPath }}/func-functionsapp.parameters.json -name "${{ github.event.inputs.funcName }}" -funcVersion "${{ github.event.inputs.funcVersion }}" -workName "${{ github.event.inputs.workName }}" -stName "${{ github.event.inputs.stName }}" -appiKey "${{ github.event.inputs.appiKey }}" -appiConnection "${{ github.event.inputs.appiConnection }}" -funcRuntime "dotnet-isolated" -rgEnvironment "${{ github.event.inputs.rgEnvironment }}"
                    