name: logic-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of rg- Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      logicName:
        description: 'Name of the logic- resource - Example: logic-WORKFLOW-ENVIRONMENT-001'
        required: true
        type: string
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.logicName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/LogicApp.json --parameters  ${{ github.event.inputs.armPath }}/LogicApp.parameters.json ${{ github.event.inputs.logicParameters }}
                    