name: npm-test-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      scriptsPath:
        description: 'Path to PowerShell and CMD scripts - Default: github.workspace/scripts'
        required: false
        type: string
        default: '${{ github.workspace }}/scripts'
      srcPath:
        description: 'Path to node.js source project - Default: github.workspace/src'
        required: false
        type: string
        default: '${{ github.workspace }}/src'
      nodeVersion:
        description: 'Mask to node.js version - Default: 17.x'
        required: false
        type: string
        default: '17.x'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Set-Version.ps1
      shell: powershell
      run: ${{ github.event.inputs.scriptsPath }}/Set-Version.ps1 --Path ${{ github.event.inputs.srcPath }} --VersionToReplace ${{ github.event.inputs.srcVersionToReplace }}
    - name: Install Node.js ${{ github.event.inputs.nodeVersion }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ github.event.inputs.nodeVersion }}
    - name: npm install
      run: npm install ${{ github.event.inputs.srcPath }}
    - name: npm run test
      run: npm run test ${{ github.event.inputs.srcPath }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.inputs.artifactsPath }}
        name: drop
                    