name: npm-build-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      archiveFile:
        description: 'Mask to artifact compressed filename - Default: archive.zip'
        required: false
        type: string
        default: 'archive.zip'
      scriptsPath:
        description: 'Path to PowerShell and CMD scripts - Default: github.workspace/scripts'
        required: false
        type: string
        default: '${{ github.workspace }}/scripts'
      srcPath:
        description: 'Path to node.js source project - Default: github.workspace/src'
        required: false
        type: string
        default: '${{ github.workspace }}/src'
      tempPath:
        description: 'Path to temporary files working folder - Default: github.workspace/ymltemp'
        required: false
        type: string
        default: '${{ github.workspace }}/ymltemp'
      nodeVersion:
        description: 'Mask to node.js version - Default: 17.x'
        required: false
        type: string
        default: '17.x'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Set-Version.ps1
      shell: powershell
      run: ${{ github.event.inputs.scriptsPath }}/Set-Version.ps1 --Path ${{ github.event.inputs.srcPath }} --VersionToReplace ${{ github.event.inputs.srcVersionToReplace }}
    - name: Install Node.js ${{ github.event.inputs.nodeVersion }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ github.event.inputs.nodeVersion }}
    - name: npm install
      run: npm install ${{ github.event.inputs.srcPath }}
    - name: npm run build
      run: npm run build ${{ github.event.inputs.srcPath }}
    - name: copy wwwroot
      run: Copy '${{ github.event.inputs.srcPath }}/wwwroot/**' '${{ github.event.inputs.tempPath }}'
    - name: Archive ${{ github.event.inputs.archiveFile }}
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ${{ github.event.inputs.artifactsPath }}/${{ github.event.inputs.archiveFile }} ${{ github.event.inputs.tempPath }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.inputs.artifactsPath }}
        name: drop
                    