name: nuget-deploy-external-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      nugetApiKey:
        description: 'Nuget.org API Key (guid) to use for deployment - Default: secrets.NUGET_API_KEY'
        required: false
        type: string
        default: ${{ secrets.NUGET_API_KEY }}
      nugetFile:
        description: 'Mask to nuget file to deploy - Default: *.nupkg'
        required: false
        type: string
        default: '*.nupkg'
      nugetVersion:
        description: 'Mask to node.js version - Default: latest'
        required: false
        type: string
        default: 'latest'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.event.inputs.artifactsPath }}
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ github.event.inputs.nugetApiKey }}
        nuget-version: ${{ github.event.inputs.nugetVersion }}
    - run: nuget push