name: sb-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of rg- Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      sbName:
        description: 'Name of the sb- resource - Example: sb-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      sbSku:
        description: 'Sku of the sb- resource - Example: Basic'
        required: false
        type: choice
        default: 'Basic'
        options:
          - 'Basic'
          - 'Standard'
          - 'Premium'
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.sbName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/sb-servicebus.json --parameters  ${{ github.event.inputs.armPath }}/sb-servicebus.parameters.json -name "${{ github.event.inputs.sbName }}" -sku "${{ github.event.inputs.sbSku }}"
                    