name: sb-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of rg- Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      sqlName:
        description: 'Name of the sql- SQL Server resource - Example: sql-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      sqlUser:
        description: 'Name of the sql- SQL Server Administrator - Example: MyLocalAdmin'
        required: true
        type: string
      sqlPassword:
        description: 'Name of the sql- SQL Server Administrator Password - Example: MyLocalAdmin'
        required: true
        type: string
      sqldbName:
        description: 'Name of the SQL Server Database - Example: 00000000-0000-0000-0000-000000000000'
        required: true
        type: string
      sqldbSku:
        description: 'Sku of the SQL Server Database - Example: Basic'
        required: false
        type: choice
        default: 'Basic'
        options:
          - 'Basic'
          - 'Standard'
          - 'Premium'
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.sqldbName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/sqldb-sqldatabase.json --parameters  ${{ github.event.inputs.armPath }}/sqldb-sqldatabase.parameters.json -name "${{ github.event.inputs.sqldbName }}" -sku "${{ github.event.inputs.sqlDatabaseSku }}"
                    