name: web-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      appiKey:
        description: 'Key (guid) of the appi resource - Example: 00000000-0000-0000-0000-000000000000'
        required: true
        type: string
      appiConnection:
        description: 'Connection string of the appi resource - Example: InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://REGION.in.applicationinsights.azure.com...'
        required: true
        type: string
      rgEnvironment:
        description: 'Environment string of the Azure Resource Group - Default: Development'
        required: false
        type: string
        default: 'Development'
      planName:
        description: 'Name of the plan- App Service Plan resource - Example: plan-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      planSku:      
        description: 'Sku of the plan- resource - Example: F1'
        required: false
        type: choice
        default: 'F1'
        options:
          - 'F1'
          - 'D1'
          - 'B1'
          - 'B2'
          - 'B3'
          - 'S1'
          - 'S2'
          - 'S3'
          - 'P1'
          - 'P2'
          - 'P3'
          - 'P4'
          - 'Y1'
      webName:
        description: 'Name of the web- resource to deploy - Example: web-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.planName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/plan-appplan.json --parameters  ${{ github.event.inputs.armPath }}/plan-appplan.parameters.json -name "${{ github.event.inputs.planName }}" -sku "${{ github.event.inputs.planSku }}"
    - name: Deploy ${{ github.event.inputs.webName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/web-webapp.json --parameters  ${{ github.event.inputs.armPath }}/web-webapp.parameters.json -name "${{ github.event.inputs.webName }}" -planName "${{ github.event.inputs.planName }}"
                    