name: web-deploy-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      archiveFile:
        description: 'Mask to artifact compressed filename - Default: *.zip'
        required: false
        type: string
        default: '*.zip'
      webName:
        description: 'Name of the web- resource to deploy - Example: web-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ secrets.AZURE_CREDENTIALS  }}

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.event.inputs.artifactsPath }}
    - name: Deploying ${{ github.event.inputs.webName }}
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.webName }}
        package: ${{ github.event.inputs.artifactsPath }}/**/${{ github.event.inputs.archiveFile }}
                    