// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace dotnet_semantickernel.Specs.Application.Unit.Forecasts.Queries.Get
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Get Forecast Query")]
    [NUnit.Framework.CategoryAttribute("getForecastQuery1")]
    public partial class GetForecastQueryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "getForecastQuery1"};
        
#line 1 "GetForecastQuery.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Forecasts/Queries/Get", "Get Forecast Query", "As a weather forecasts user\r\nI can get a weather forecast", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get forecast")]
        [NUnit.Framework.TestCaseAttribute("success Freezing", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "32", "Freezing", null)]
        [NUnit.Framework.TestCaseAttribute("success Bracing", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "33", "Bracing", null)]
        [NUnit.Framework.TestCaseAttribute("success Chilly", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "41", "Chilly", null)]
        [NUnit.Framework.TestCaseAttribute("success Cool", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "51", "Cool", null)]
        [NUnit.Framework.TestCaseAttribute("success Mild", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "61", "Mild", null)]
        [NUnit.Framework.TestCaseAttribute("success Warm", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "71", "Warm", null)]
        [NUnit.Framework.TestCaseAttribute("success Balmy", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "81", "Balmy", null)]
        [NUnit.Framework.TestCaseAttribute("success Hot", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "91", "Hot", null)]
        [NUnit.Framework.TestCaseAttribute("success Sweltering", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "101", "Sweltering", null)]
        [NUnit.Framework.TestCaseAttribute("success Scorching", "Success", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "true", "111", "Scorching", null)]
        [NUnit.Framework.TestCaseAttribute("not found", "NotFound", "", "038d8e7f-f18f-4a8e-8b3c-3b6a6889fed9", "false", "0", "Cool", null)]
        [NUnit.Framework.TestCaseAttribute("bad request: empty key", "BadRequest", "Key", "", "false", "0", "Cool", null)]
        public void GetForecast(string def, string response, string responseErrors, string key, string forecastExists, string expectedTemperatureF, string expectedSummaryResponse, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("def", def);
            argumentsOfScenario.Add("response", response);
            argumentsOfScenario.Add("responseErrors", responseErrors);
            argumentsOfScenario.Add("key", key);
            argumentsOfScenario.Add("forecastExists", forecastExists);
            argumentsOfScenario.Add("expectedTemperatureF", expectedTemperatureF);
            argumentsOfScenario.Add("expectedSummaryResponse", expectedSummaryResponse);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get forecast", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("I have a definition \"{0}\"", def), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("I have a forecast key \"{0}\"", key), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And(string.Format("I have a forecast exists \"{0}\"", forecastExists), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And(string.Format("I have a expected temperatureF response \"{0}\"", expectedTemperatureF), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And(string.Format("I have a expected summary response \"{0}\"", expectedSummaryResponse), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.When("I get a forecast", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then(string.Format("The response is \"{0}\"", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
 testRunner.And("If the response is successful the response has a Key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.And("If the response is successful The response has a Date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.And("If the response is successful The response has a TemperatureF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
 testRunner.And("If the response is successful The response has a Zipcodes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
 testRunner.And(string.Format("If the response is successful The response has a valid Summary of \"{0}\"", expectedSummaryResponse), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 testRunner.And(string.Format("If the response has validation issues I see the \"{0}\" in the response", responseErrors), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
