trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/lz-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_app_configuration
        steps:
          - template: steps/appcs-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'

      - job: deploy_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/infrastructure-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              apiName: '$(apiName)'
              appiKey: '$(appiKey)'
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              planName: '$(planName)'
              sqlName: '$(sqlName)'
              sqlSku: '$(sqlSku)'
              sqlLocation: '$(sqlLocation)'
              sqlUser: '$(sqlUser)'
              sqlPassword: '$(sqlPassword)'
              sqlDatabase: '$(sqlDatabase)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'
              stName: '$(stName)'
              webName: '$(webName)'
              workName: '$(workName)'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml    

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/lz-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_infrastructure
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/infrastructure-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              apiName: '$(apiName)'
              appiKey: '$(appiKey)'
              appiConnection: '$(appiConnection)'
              funcName: '$(funcName)'
              planName: '$(planName)'
              sqlName: '$(sqlName)'
              sqlSku: '$(sqlSku)'
              sqlLocation: '$(sqlLocation)'
              sqlUser: '$(sqlUser)'
              sqlPassword: '$(sqlPassword)'
              sqlDatabase: '$(sqlDatabase)'
              sbName: '$(sbName)'
              sbSku: '$(sbSku)'
              stName: '$(stName)'
              webName: '$(webName)'
              workName: '$(workName)'